linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gosimple
    - gocritic
    - revive
    - misspell
    - gofmt
    - goimports

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
  revive:
    rules:
      - name: exported
      - name: var-naming
      - name: error-return
      - name: error-strings
      - name: unexported-return

run:
  timeout: 5m

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
